version: '3'

services:
  app:
    build: ./app
    ports: 
      - "8080:8080"
    container_name: front-container
    restart: always
    links:
      - server

  server:
    build: ./server
    ports: 
      - "3000:3000"
    container_name: back-container
    restart: always
